GGK/Assets/Scripts/API/APIManager.cs, GGK/Assets/Scripts/DriverScripts/PlacementManager.cs, GGK/Assets/Scripts/ItemScripts/ItemHolder.cs
I fixed the build error stemming from unneeded includes
=> Fixed Build error

GGK/Assets/Scripts/DriverScripts/NEWDriver.cs
There was code that needed an audio reference which we did not have in main. To prevent errors popping up, I uncommented the code. It will be commented back again once the audio setup is finalized
=> Uncommented code that was popping errors

GGK/Assets/Prefabs/Kart 1.prefab, GGK/Assets/Scenes/PolishingPhysics.unity, GGK/Assets/Scenes/PolishingPhysics.unity.meta, GGK/Assets/Scripts/DriverScripts/NEWDriver.cs
Polished driver and camera settings for better feeling kart. All of these changes are encapsulated into a new scene. The changes made to the prefab were applied to the original prefab, so everyone can use the better settings
=> Polishing physics

GGK/Assets/Scenes/GameOverScene.unity, GGK/ProjectSettings/ProjectSettings.asset
Return To Map Select & Return To Start buttons. I just hook them up to a script (GameOverMenuHandeler) and methods that already exist.
=> Added Buttons to GameOverScene

GGK/Assets/InputSystem.inputsettings.asset, GGK/Assets/InputSystem.inputsettings.asset.meta, GGK/ProjectSettings/EditorBuildSettings.asset, GGK/ProjectSettings/ProjectSettings.asset
I'm only opening a pull request to test the automated building
=> Do not merge (until I say so)

GGK/Assets/Scenes/RIT Outer Loop Greybox.unity
fixing minimap position, size again because I'm not sure why they were left out of last merge
=> Updating HUD Map elements

GGK/Assets/Scenes/RIT Outer Loop Greybox.unity, GGK/Assets/Scripts/DriverScripts/NPCDriver.cs, GGK/Assets/Scripts/ItemScripts/ItemHolder.cs
Refining the physics of the NPC and allow the NPC to use item (some items still need fixes in order for npc to use)
=> Refining the physics of npc

GGK/Assets/Prefabs/CharacterButton.prefab, GGK/Assets/Prefabs/CharacterButton.prefab.meta, GGK/Assets/Scenes/PlayerKartScene.unity, GGK/Assets/Scripts/GameManagers/PlayerKartHandeler.cs
Made it more closely match the example from content team's week 3 retrospective example. Probably should've waited until a final design or let them implement the design?
=> Design Change for PlayerKart Scene

GGK/Assets/Scenes/RIT Outer Loop Greybox.unity, GGK/Assets/Scripts/ItemScripts/ItemBoxManager.cs
Adjust the script of the Item box manager so that it can reference all the item boxes in the scene and attach the script to the manager
=> Item box manager adjustment

GGK/Assets/Scripts/ItemScripts/ItemHolder.cs, GGK/Assets/Scripts/Obstacle.cs
- Also tweaked the boost so NPCs can use it
=> Terrain slow down added for NPC karts

GGK/.github/copilot-instructions.md, GGK/Assets/Scenes/RIT Outer Loop Greybox.unity, GGK/Assets/Scenes/StartScene.unity, GGK/Assets/Scripts/GameManagers/GameManager.cs, GGK/ProjectSettings/ProjectSettings.asset
Added a method to GameManager for "Quiting Game" functionality so the user can quit the game without having to do alt + f4. This is on a button in the start scene. Also tried putting default texture in for item display in RIT Outerloop
=> Exit Game Button implemented

GGK/Assets/Prefabs/OptionsPanel.prefab, GGK/Assets/Scripts/GameManagers/OptionsData.cs, GGK/Assets/Scripts/GameManagers/OptionsHandler.cs
Volume separated into master volume, dialogue volume, sfx volume, and music volume
=> Made volume into 4 separate thing

.github/ISSUE_TEMPLATE/todo-task.md
Updated TODO task. Replaced example text with text instructing the user on the content of the issue.
=> Update issue templates

GGK/Assets/Scenes/PlayerKartScene.unity
Readded confirm button to playerOptions list I didn't realize this was missing
=> Emergency Fix

GGK/.github/copilot-instructions.md, GGK/Assets/Scenes/MapSelectScene.unity, GGK/Assets/Scenes/PlayerKartScene.unity, GGK/Assets/Scripts/GameManagers/GameManager.cs, GGK/ProjectSettings/EditorBuildSettings.asset
The Quarter Mile and Finals Brick Road have been added as selectable maps on the map select. I also fixed a bug where you were unable to progress past the player select scene.
=> More maps on map select

GGK/Assets/Scenes/PlayerKartScene.unity, GGK/Assets/Scripts/GameManagers/PlayerKartHandeler.cs, GGK/Assets/Scripts/PlayerSelect/PlayerKartModel.cs, GGK/Assets/Scripts/PlayerSelect/PlayerKartModel.cs.meta
Why did I spend my time doing this? It is not like the canvas elements change size if we squish it on the x-axis. (Basically the playerKart Scene still looks bad on what I think are unrealistic resolution ratios?)
The character buttons not aligning with the orange stripe might be able to be solved if I get it as a separate image, not sure how high priority that is.
Anyways the kart model now moves better with the canvas/screen if you drag it up, down, left or right
Also moved some rotation code from playerkarthandeler into playerkartmodel which apply logic solely to the player kart model
=> kart model now moves better with screen size changes

GGK/Assets/Prefabs/Leaderboard.prefab, GGK/Assets/Prefabs/LeaderboardItem.prefab, GGK/Assets/Scenes/LeaderboardTest.unity, GGK/Assets/Scripts/HUDScripts/Leaderboard Controller.cs
Made mainly size and position changes to the leaderboard and leaderboard prefabs
Added one line of code to leaderboard controller script such that the leaderboard item properly fits inside the leaderboard game object when instantiated
=> Corrected Leaderboard stuff for new canvas reference resolution

GGK/Assets/Prefabs/ItemBox.prefab, GGK/Assets/Scenes/RIT Outer Loop Greybox.unity
Fix small issue with itemBox manager. For the sake of testing for Thursday, item box list will be reduced to 3 items to avoid confusion when pick up item and land on null item
=> Fix small issue with item box

GGK/Assets/Scenes/RIT Dorm Greybox.unity
Scale the checkpoint to fill the shortcut
=> Dorm checkpoint

GGK/.github/copilot-instructions.md, GGK/Assets/Crossfade.controller, GGK/Assets/Scenes/Dorm_LevelDesign.unity, GGK/Assets/Scenes/MapSelectScene.unity, GGK/Assets/Scenes/PlayerKartScene.unity, GGK/Assets/Scenes/StartScene.unity, GGK/Assets/Scripts/GameManagers/GameManager.cs, GGK/ProjectSettings/EditorBuildSettings.asset
Updated map select to have updated maps
Transition between scenes is faster
Kart has set position now in player select scene
=> Playtest 1 menu updates

GGK/Assets/Prefabs/Kart 1.prefab, GGK/Assets/Scenes/V2 RIT Outer Loop Greybox.unity, GGK/Assets/Scripts/DriverScripts/NEWDriver.cs
Changes to the NEWDriver script + applied prefab settings
=> Fixed bugs and kart improvements from the playtest feedback

GGK/Assets/Scripts/DriverScripts/KartCheckpoint.cs
Rework the checkpoint script so that right now it will allow player to be able to cross the next 10 checkpoints instead of only 1 ahead of them. Also prevent player to trick the track
=> Checkpoint being able to allow shortcut and restrict tricking the system

GGK/Assets/Scenes/TrackScenes/GolisanoCollege/GSP_Golisano.unity
The speed display is adjusted so it isn't partly off screen
=> Adjusting the Speedbar on Golisano

GGK/Assets/Scripts/GameManagers/AudioManager.cs, GGK/Assets/Scripts/SoundScripts/SoundVolume.cs
makes it so that the music changes volume according to the master volume and music volume options settings
=> Music changes volume according to the appropriate volume settings

GGK/Assets/Scripts/ItemScripts/ItemHolder.cs
Changed how the kart is rotated towards the next checkpoint to be consistent across every track
=> Adjusted Kart rotation

GGK/Assets/Scenes/PlayerKartScene.unity, GGK/Assets/Scripts/GameManagers/PlayerKartHandeler.cs
selected character icon now changes color to the selected color better
=> Addressing Issue #279

GGK/Assets/Scenes/Race Mode Stubs/GrandPrixStub.unity, GGK/Assets/Scenes/Race Mode Stubs/TimeTrialStub.unity, GGK/Assets/Scenes/TrackScenes/DormRoom/GSP_RITDorm.unity, GGK/Assets/Scenes/TrackScenes/GolisanoCollege/GSP_Golisano.unity, GGK/Assets/Scenes/TrackScenes/OuterLoop/GSP_RITOuterLoop.unity, GGK/Assets/Scenes/TrackScenes/QuarterMile/GSP_RITQuarterMile.unity, GGK/Assets/Scripts/GameManagers/GameManager.cs
Players can navigate the Pause Menu on controller
"Return to Map" is reworded "Return to Map Select" in the Pause Menu
The Grand Prix and Time Trial menus are navigable using controller
=> More controller support in menus

GGK/Assets/Scripts/DriverScripts/KartCheckpoint.cs, GGK/Assets/Scripts/HUDScripts/Leaderboard Controller.cs
Fix the checkpoint system so that the player can take shortcut and don't need to cross the very last checkpoint to finish a lap. Also fixing a bug derive from this where the the placement did not updated when the leaderboard show up which cause it to display incorrectly
=> Finish fixing checkpoint system

GGK/Assets/Scenes/GameModeSelectScene.unity
the position of the buttons and title of the game mode select scene are adjusted so it doesn't start to hit the bottom of the screen
=> GameMode select scene update

GGK/Assets/Scenes/GameModeSelectScene.unity
This was something I missed in my initial changes. The game mode select scene had everything off center and had inconsistent naming for the title textmeshpro so now it updated to say "Game Mode Select" rather than "Race Mode Select"
=> Centered menu in game mode select + updated title in game mode select

GGK/Assets/Materials/ShieldMaterial.mat, GGK/Assets/Scripts/ItemScripts/ItemBox.cs, GGK/Assets/Scripts/ItemScripts/ItemHolder.cs
remade boost level 3 to make it look better, now gives kart hover craft effect
=> Boost upgrades

GGK/Assets/Prefabs/UpgradeBrick.prefab, GGK/Assets/Prefabs/UpgradeBrick.prefab.meta, GGK/Assets/Scenes/TestingScenes/TrapItemTest.unity, GGK/Assets/Scripts/ItemScripts/ItemHolder.cs, GGK/Assets/Scripts/ItemScripts/UpgradeBrick.cs, GGK/Assets/Scripts/ItemScripts/UpgradeBrick.cs.meta
- When you run into an upgrade brick without an item the upgraded tier is stored and activates when you get any of the 4 item type immediately getting the corresponding tier of that item type
- Upgrade system now uses driverItemTier to keep track of current itemTier
=> Upgrade Brick Functionality + Upgrade system uses DriverItemTier

GGK/Assets/Prefabs/NPCKart.prefab, GGK/Assets/Scenes/TrackScenes/OuterLoop/GSP_RITOuterLoop.unity, GGK/Assets/Scripts/DriverScripts/NPCPhysics.cs, GGK/ProjectSettings/Packages/com.unity.learn.iet-framework/Settings.json, GGK/ProjectSettings/ProjectSettings.asset
=> Npc in more maps

GGK/Assets/Scripts/DriverScripts/KartVisual.cs, GGK/Assets/Scripts/DriverScripts/NEWDriver.cs
=> Fixed a bug on KartVisual and changed a few numbers for better drift 

GGK/.github/copilot-instructions.md, GGK/Assets/Prefabs/Kart 1.prefab, GGK/Assets/Prefabs/PlacementManager.prefab, GGK/Assets/Prefabs/PlacementManager.prefab.meta, GGK/Assets/Scenes/StartScene.unity, GGK/Assets/Scenes/TrackScenes/DormRoom/GSP_RITDorm.unity, GGK/Assets/Scenes/TrackScenes/OuterLoop/GSP_RITOuterLoop.unity, GGK/Assets/Scripts/DriverScripts/NEWDriver.cs, GGK/Assets/Scripts/DriverScripts/SpeedCameraEffect.cs, GGK/Assets/Scripts/HUDScripts/MiniMapHud.cs, GGK/Assets/Scripts/PlayerSpawner.cs
Fix kart spawning feature and implement them in Dorm, Outer Loop and Finals Brick Road, will implement in Golisano later
=> NPC spawning

GGK/.github/copilot-instructions.md, GGK/Assets/Scenes/TrackScenes/GolisanoCollege/GSP_Golisano.unity, GGK/Assets/Scenes/TrackScenes/OuterLoop/GSP_RITOuterLoop.unity, GGK/Assets/Scripts/DriverScripts/NPCPhysics.cs, GGK/Assets/Scripts/GameManagers/MultiplayerSceneManager.cs
Added player in the golisano map
=> Mp placement tracking syncing

GGK/Assets/Prefabs/Kart 1.prefab
There are a few changes to particles made in the moment bc I thought it would look better 🕺
=> Kart model sync: Model animations, drift animations, wheel animations

GGK/Assets/Scenes/Race Mode Stubs/GrandPrixStub.unity, GGK/Assets/Scenes/Race Mode Stubs/TimeTrialStub.unity, GGK/Assets/Scripts/GameManagers/BackButtonHandler.cs, GGK/Assets/Scripts/GameManagers/RaceModeStubHandeler.cs
- back button on the race mode select scene leaves the lobby if the player is in one, and ends the lobby (by kicking all players) if they are the host
- grand prix and time trial stubbed scenes only go back to the game modes rather than also having start
=> Back button update

GGK/Assets/Scripts/DriverScripts/NEWDriver.cs, GGK/Assets/Scripts/DriverScripts/NPCPhysics.cs
Placement for both client and host along with NPCs is now has been fix in multiplayer
=> Placement fix

GGK/Assets/CarControls.cs, GGK/Assets/CarControls.inputactions, GGK/Assets/Materials/dev_texture_dirt.mat, GGK/Assets/Materials/dev_texture_door_i.mat, GGK/Assets/Materials/dev_texture_hazard.mat, GGK/Assets/Materials/dev_texture_metal.mat, GGK/Assets/Materials/dev_texture_misc.mat, GGK/Assets/Materials/dev_texture_plant.mat, GGK/Assets/Materials/dev_texture_plastic.mat, GGK/Assets/Materials/dev_texture_road.mat, GGK/Assets/Materials/dev_texture_wood.mat, GGK/Assets/Materials/dev_texture_yellow.mat
pulling current wheel implementation into main.
=> Wheel implementation

GGK/Assets/Scripts/DriverScripts/KartCheckpoint.cs
Changed the lap total in KartCheckpoint.cs to make the races three laps each.
=> made the races three laps each

GGK/Assets/Scripts/API/APIManager.cs, GGK/Assets/Scripts/GameManagers/GameManager.cs, GGK/Assets/Scripts/Keyboard/VirtualKeyboardController.cs, GGK/Assets/Scripts/LoginScripts/SignInManager.cs
Log in and sign up now have validation checks built in as well as refactored code to utilize threading and more callbacks.
=> Api improvements

GGK/Assets/Scenes/Login.unity, GGK/Assets/Scripts/LoginScripts/PasswordHider.cs, GGK/Assets/Scripts/LoginScripts/PasswordHider.cs.meta, GGK/Assets/Scripts/LoginScripts/SignInManager.cs
This branch integrates a toggle for hiding the password
=> Password can be hidden

GGK/Assets/Scripts/DriverScripts/KartCheckpoint.cs, GGK/Assets/Scripts/HUDScripts/Leaderboard Controller.cs
Leaderboard now display the same information across the servers and clients as well as shows up at the same time. The game ends once all players cross the finish line.
=> Leaderboard display & End Game fix

GGK/.github/copilot-instructions.md, GGK/ProjectSettings/ProjectSettings.asset
Set default screen width/height to 1600/900 and set resizable window to true. This allows the screen to resize when necessary.
=> Changing default resolution

GGK/Assets/Scripts/GameManagers/GameManager.cs, GGK/Assets/Scripts/GameManagers/MultiplayerManager.cs
Can select finals brick road now when in multiplayer
=> Multiplayer in more maps

GGK/Assets/Scenes/TrackScenes/OuterLoop/GSP_RITOuterLoop.unity
Fix the bugs where the outer loop is completely freezing in multiplayer
=> Fixing outerloop freezing

GGK/Assets/Scenes/MapSelectScene.unity
Fixed the bug where you were unable to navigate the map select scene on controller
=> Controller working on Map Select

GGK/Assets/Scripts/DriverScripts/KartCheckpoint.cs, GGK/Assets/Scripts/HUDScripts/Leaderboard Controller.cs
The kart we play will appear with a different color on the leaderboard to differentiate (works on both single and multiplayer).
=> Leaderboard now have our kart in different color 

GGK/Assets/Scenes/TrackScenes/All-Nighter Expressway/GSP_FinalsBrickRoad.unity
The Road was not tagged as "Road", which made the kart think it was off road
=> fixed slow speed after falling off

GGK/Assets/Scenes/TrackScenes/DormRoom/GSP_RITDorm.unity, GGK/Assets/Scenes/TrackScenes/FinalsBrickRoad/GSP_FinalsBrickRoad.unity, GGK/Assets/Scenes/TrackScenes/GolisanoCollege/GSP_Golisano.unity, GGK/Assets/Scenes/TrackScenes/OuterLoop/GSP_RITOuterLoop.unity, GGK/Assets/Scripts/PlayerSpawner.cs
Spawning now works consistently throughout all the maps
=> Try fix spawning

GGK/Assets/Scenes/TrackScenes/OuterLoop/GSP_RITOuterLoop.unity
pause menu on outer loop is fixed for the gsp scene of the track
=> pause menu fixed on gsp version

GGK/.github/copilot-instructions.md, GGK/Assets/Prefabs/ItemPrefabs/Hazard/HazardTier2.prefab, GGK/Assets/Prefabs/ItemPrefabs/Hazard/HazardTier2.prefab.meta, GGK/Assets/Prefabs/ItemPrefabs/Hazard/HazardTier3.prefab, GGK/Assets/Prefabs/ItemPrefabs/Hazard/HazardTier3.prefab.meta, GGK/Assets/Prefabs/ItemPrefabs/Hazard/HazardTier4.prefab, GGK/Assets/Prefabs/ItemPrefabs/Hazard/HazardTier4.prefab.meta, GGK/Assets/Prefabs/ItemPrefabs/Puck/PuckTier1.prefab, GGK/Assets/Prefabs/Kart 1.prefab, GGK/Assets/Prefabs/MultiplayerNPC.prefab, GGK/Assets/Prefabs/NPCKart.prefab, GGK/Assets/Scenes/StartScene.unity, GGK/Assets/Scripts/ItemScripts/Hazards/HazardTier2.cs, GGK/Assets/Scripts/ItemScripts/Hazards/HazardTier2.cs.meta, GGK/Assets/Scripts/ItemScripts/Hazards/HazardTier3.cs, GGK/Assets/Scripts/ItemScripts/Hazards/HazardTier3.cs.meta, GGK/Assets/Scripts/ItemScripts/Hazards/HazardTier4.cs, GGK/Assets/Scripts/ItemScripts/Hazards/HazardTier4.cs.meta, GGK/Assets/Scripts/ItemScripts/ItemHolder.cs
Changed the order of Hazard Items
Tier 1 -> 1
Tier 2 -> 3
Tier 3 -> 4
Tier 4 -> 2
Increased threat coverage of Cracked Brick Wall and Blizzard
=> Items hazards ordering change

GGK/Assets/Scenes/TrackScenes/All-Nighter Expressway/GSP_FinalsBrickRoad.unity, GGK/Assets/Scenes/TrackScenes/DormRoom/LD_RITDorm.unity, GGK/Assets/Scenes/TrackScenes/OuterLoop/LD_RITOuterLoop.unity, GGK/ProjectSettings/EditorBuildSettings.asset
swapped out pause panel prefab for pause prefab in all three scenes
Additionally added mini map to the LD RITOuterLoop Scene, it was missing for some reason and is necessary for the code to not silently fails which causes my own the code to dynamically hook up pause menu to controls not running
=> Pause Stuff

GGK/Assets/Scenes/TrackScenes/All-Nighter Expressway/GSP_FinalsBrickRoad.unity, GGK/Assets/Scenes/TrackScenes/GolisanoCollege/GSP_Golisano.unity, GGK/Assets/Scripts/DriverScripts/BoostPanel.cs, GGK/Assets/Scripts/DriverScripts/NPCPhysics.cs
NPC now can use the boost panel and can fix itself when running perpendicular to a wall.
=> Npc enhancement

GGK/Assets/Scenes/TrackScenes/DormRoom/LD_RITDorm.unity, GGK/Assets/Scripts/DriverScripts/NPCPhysics.cs
Update Dorm checkpoint and improve NPC backing out when running into an obstacle perpendicular
=> Dorm checkpoint and NPC enhancement

GGK/Assets/Scenes/GrandPrixSelectScene.unity, GGK/Assets/Scenes/GrandPrixSelectScene.unity.meta, GGK/Assets/Scripts/GameManagers/GameManager.cs, GGK/Assets/Scripts/GameManagers/GameModeHandeler.cs, GGK/Assets/Scripts/GameManagers/GrandPrixSelectHandler.cs, GGK/Assets/Scripts/GameManagers/GrandPrixSelectHandler.cs.meta, GGK/ProjectSettings/EditorBuildSettings.asset
It should work, but couldn't test properly because still can't drive on golisano or brick road.
When is the fix coming
=> grandprix mode

GGK/Assets/Prefabs/Kart 1.prefab, GGK/Assets/Scripts/DriverScripts/NEWDriver.cs, GGK/Assets/Scripts/GameManagers/MultiplayerManager.cs
=> Fix look back

GGK/Assets/Scripts/DriverScripts/KartCheckpoint.cs
=> KEEP IT 3 LAPS

GGK/Assets/Scripts/DevTools.cs
GiveItem does not yet work in multiplayer but load scene and map will bring all players to that scene or map (when called by server), and will keep players in lobby if brought to a scene before the lobby one (like start) if then brought back to a map from prompt.
=> LoadMap and LoadScene work in multiplayer

GGK/Assets/Prefabs/Kart 1.prefab, GGK/Assets/Scripts/DriverScripts/NEWDriver.cs
changes made to drifting and general driving. Branch is not updated with main so there might be merge errors. The important file is to get the changes from is NEWDriver, the rest is easily fixed
=> Drift feel changes

GGK/Assets/Scripts/Keyboard/VirtualKeyboardController.cs
=> Virtual keyboard touch ups

GGK/Assets/Prefabs/Kart 1.prefab, GGK/Assets/Scripts/DriverScripts/NEWDriver.cs, GGK/Assets/Scripts/DriverScripts/VFX handler/VFXHandler.cs
Fixed vfx bug, shortened min drift time from 130 to 110. Patched turbotwist bug
=> A few fixes and touch ups.

GGK/Assets/Scenes/TrackScenes/All-Nighter Expressway/TT_FinalsBrickRoad.unity, GGK/Assets/Scenes/TrackScenes/DormRoom/TT_RITDorm.unity, GGK/Assets/Scenes/TrackScenes/GolisanoCollege/TT_Golisano.unity, GGK/Assets/Scenes/TrackScenes/OuterLoop/TT_RITOuterLoop.unity
I missed adding the placement number sprites into the placement manager this causes update to fail at the switch which means the code to update lap counter does not happen
Anyways noticed it and fixed it
=> Lap counter should work in Time Trials now

GGK/Assets/Prefabs/Kart 1.prefab, GGK/Assets/Scenes/MultiplayerConnectionBufferScene.unity
Create a multiplayer scene and when get to a buffer scene, hover over the color to see if the color of the text change to yellow
=> Change the button effect in multiplayer buffer scene

GGK/Assets/Scripts/DriverScripts/NEWDriver.cs, GGK/Assets/Scripts/HUDScripts/Leaderboard Controller.cs
The player no longer moves after the race ends
=> No more movement after race

GGK/Assets/Scripts/DriverScripts/NEWDriver.cs
Took away turning as well so the player was not spinning out.
=> No movement after race

GGK/Assets/Scenes/MultiplayerConnectionBufferScene.unity, GGK/Assets/Scenes/TrackScenes/OuterLoop/LD_RITOuterLoop-Backup.unity, GGK/Assets/Scenes/TrackScenes/OuterLoop/TT_RITOuterLoop.unity
also adjusted position of time display in outer loop
=> button hover fix - multiplayer connect
